// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace test
{
	public partial class SameProjSBViewController : UIViewController
	{
		public SameProjSBViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);

			SecondText.Text = "why did you work";
		}
	}
}
